name: TodayMood 
options: 
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: com.5boon
  deploymentTarget:
     iOS: "12.0"
targets:
  TodayMood:
    type: application
    platform: iOS 
    deploymentTarget: "12.0"
    info:
      path: TodayMood/Supporting Files/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    settings:
      INFOPLIST_FILE: TodayMood/Supporting Files/Info.plist
    sources: 
      - TodayMood/Sources
      - path: "TodayMood/Supporting Files"
        type: group
      - path: "TodayMood/Supporting Files/GoogleService-Info.plist"
        buildPhase: resources
      - path: TodayMood/Resources
        type: group
    postCompileScripts:
    - script: "${PODS_ROOT}/SwiftLint/swiftlint"
      name: Swiftlint
  TodayMoodTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - TodayMoodTests
    dependencies:
      - target: TodayMood