name: CI
on: [push]
jobs:
  run:
    runs-on: macOS-latest
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["11"]
        env:
          - sdk: iphonesimulator12.2
            destination: platform=iOS Simulator,name=iPhone XS,OS=12.2
    steps:
    - uses: actions/checkout@v1
    - name: Install and run xcodegen
      run: |
        brew install xcodegen
        xcodegen generate
    - name: Set Xcode
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing Xcode_${{ matrix.xcode }}.app"
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version
        swift --version
        swift package --version
    - name: Install Dependences
      run: |
        gem install cocoapods 
        pod install
    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env: 
        PROJECT: TodayMood.xcodeproj
        SCHEME: TodayMood
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Github Actions*'
        mention: 'here'
        mention_if: 'failure'
        channel: '#logs'
        url: ${{ secrets.SLACK_WEBHOOK }}
