name: CI
on: [push]
jobs:
  run:
    runs-on: macOS-latest
    name: Xcode ${{ matrix.xcode }}
    strategy:
      matrix:
        xcode: ["11"]
    steps:
    - uses: actions/checkout@v1
    - name: Install and run xcodegen
      run: |
        brew install xcodegen
        xcodegen generate
    - name: Set Xcode
      run: |
        echo "Available Xcode versions:"
        ls /Applications | grep Xcode
        echo "Choosing Xcode_${{ matrix.xcode }}.app"
        sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
        xcodebuild -version
        swift --version
        swift package --version
    - name: Install Dependences
      run: bundle exec pod install
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Github Actions*'
        mention: 'here'
        mention_if: 'failure'
        channel: '#logs'
        url: ${{ secrets.SLACK_WEBHOOK }}
